backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Path", name: "path", widget: "string"}

  - name: "quick"
    label: "Quick Start Guides"
    folder: "src/pages/quick-start-guides"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Path", name: "path", widget: "string"}

  - name: "meditations"
    label: "Meditations"
    folder: "src/pages/meditations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "meditation-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Path", name: "path", widget: "string"}

  - name: "fitness"
    label: "Fitness"
    folder: "src/pages/fitness"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "fitness-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Path", name: "path", widget: "string"}

  - name: "test"
    label: "Test"
    folder: "src/pages/fitness/test"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "fitness-post-child"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Path", name: "path", widget: "string"}

  - name: "weekly-meal-plans"
    label: "Weekly Meal Plans"
    folder: "src/pages/weekly-meal-plans"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "weekly-meal-plans-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Monday", name: "monday", widget: "list"}
      - {label: "Tuesday", name: "tuesday", widget: "list"}
      - {label: "Wednesday", name: "wednesday", widget: "list"}
      - {label: "Thursday", name: "thursday", widget: "list"}
      - {label: "Friday", name: "friday", widget: "list"}
      - {label: "Saturday", name: "saturday", widget: "list"}
      - {label: "Sunday", name: "sunday", widget: "list"}

  - name: "recipes"
    label: "Recipes"
    folder: "src/pages/recipes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "recipes-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Path", name: "path", widget: "string"}

  - name: "pages"
    label: "Pages"
    files:
    - file: "src/pages/index.md"
      label: "How to Get Start"
      name: "index"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
    - file: "src/pages/medical-disclaimer/index.md"
      label: "Medical Disclaimer"
      name: "medical"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "mediacal-disclaimer-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
